-- Generated by build_phase2_migration.py. Select the intended database first.
-- Applies only rail routines/guards/view and missing named constraints/indexes.
-- No table reset, seed data, database selection, global roles, or user account changes.
-- Run while rail writes are paused: MySQL DDL commits independently.
DELIMITER //
DROP PROCEDURE IF EXISTS sp_phase2_schema_checks//
CREATE PROCEDURE sp_phase2_schema_checks()
BEGIN
  IF EXISTS (SELECT 1 FROM train_trip t JOIN rail_allocation a ON a.trip_id=t.trip_id
             GROUP BY t.trip_id,t.total_capacity HAVING SUM(a.allocated_space)>t.total_capacity)
     OR EXISTS (SELECT 1 FROM order_item i JOIN rail_allocation a ON a.order_item_id=i.order_item_id
                GROUP BY i.order_item_id,i.quantity HAVING SUM(a.allocated_quantity)>i.quantity) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Rail migration blocked: existing capacity/quantity over-allocation requires review.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='train_trip' AND constraint_name='chk_trip_capacity_positive') THEN
    ALTER TABLE train_trip ADD CONSTRAINT chk_trip_capacity_positive CHECK (total_capacity > 0);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='train_trip' AND constraint_name='chk_trip_time_order') THEN
    ALTER TABLE train_trip ADD CONSTRAINT chk_trip_time_order CHECK (arrival_datetime > departure_datetime);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='train_trip' AND constraint_name='chk_trip_distinct_stations') THEN
    ALTER TABLE train_trip ADD CONSTRAINT chk_trip_distinct_stations CHECK (origin_station_id <> destination_station_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='train_trip' AND constraint_name='chk_trip_status') THEN
    ALTER TABLE train_trip ADD CONSTRAINT chk_trip_status CHECK (status IN ('SCHEDULED','IN_TRANSIT','ARRIVED','CANCELLED'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='rail_allocation' AND constraint_name='chk_alloc_qty_positive') THEN
    ALTER TABLE rail_allocation ADD CONSTRAINT chk_alloc_qty_positive CHECK (allocated_quantity > 0);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='rail_allocation' AND constraint_name='chk_alloc_space_positive') THEN
    ALTER TABLE rail_allocation ADD CONSTRAINT chk_alloc_space_positive CHECK (allocated_space > 0);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='train_trip' AND index_name='idx_f42_trip_search') THEN
    CREATE INDEX idx_f42_trip_search ON train_trip (destination_station_id, status, departure_datetime);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='rail_allocation' AND index_name='idx_f42_alloc_trip_space') THEN
    CREATE INDEX idx_f42_alloc_trip_space ON rail_allocation (trip_id, allocated_space);
  END IF;
END//
CALL sp_phase2_schema_checks()//
DROP PROCEDURE sp_phase2_schema_checks//
DELIMITER ;

-- Source: feature_4_2_rail_allocation/04_fn_order_item_space.sql
-- space needed by an order item (or by part of it)
DELIMITER //

DROP FUNCTION IF EXISTS fn_order_item_space//
CREATE FUNCTION fn_order_item_space(p_order_item_id INT, p_quantity INT)
RETURNS DECIMAL(10,2)
READS SQL DATA
BEGIN
  DECLARE v_rate DECIMAL(6,4);
  DECLARE v_qty  INT;

  SELECT p.space_consumption_rate, COALESCE(p_quantity, oi.quantity)
    INTO v_rate, v_qty
    FROM order_item oi
    JOIN product p ON p.product_id = oi.product_id
   WHERE oi.order_item_id = p_order_item_id;

  IF v_rate IS NULL THEN
    RETURN NULL;
  END IF;

  -- round UP to 2 decimals so we never under-count space
  RETURN CEILING(v_qty * v_rate * 100) / 100;
END //

DELIMITER ;

-- Source: feature_4_2_rail_allocation/05_fn_trip_remaining_capacity.sql
-- remaining space on a trip
DELIMITER //

DROP FUNCTION IF EXISTS fn_trip_remaining_capacity//
CREATE FUNCTION fn_trip_remaining_capacity(p_trip_id INT)
RETURNS DECIMAL(10,2)
READS SQL DATA
BEGIN
  DECLARE v_cap  DECIMAL(10,2);
  DECLARE v_used DECIMAL(10,2);

  SELECT total_capacity INTO v_cap FROM train_trip WHERE trip_id = p_trip_id;
  IF v_cap IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT COALESCE(SUM(allocated_space), 0) INTO v_used
    FROM rail_allocation WHERE trip_id = p_trip_id;

  RETURN v_cap - v_used;
END //

DELIMITER ;

-- Source: feature_4_2_rail_allocation/06_trg_capacity_check.sql
-- capacity CHECK as triggers (a CHECK constraint cannot look at other rows)
DELIMITER //

DROP TRIGGER IF EXISTS trg_rail_alloc_capacity_bi//
CREATE TRIGGER trg_rail_alloc_capacity_bi
BEFORE INSERT ON rail_allocation
FOR EACH ROW
BEGIN
  DECLARE v_cap    DECIMAL(10,2);
  DECLARE v_status VARCHAR(50);
  DECLARE v_used   DECIMAL(10,2);
  DECLARE v_manifest_status VARCHAR(50);

  SET NEW.allocated_space = fn_order_item_space(NEW.order_item_id, NEW.allocated_quantity);

  -- lock the trip row first: every writer for this trip queues here
  SELECT total_capacity, status INTO v_cap, v_status
    FROM train_trip WHERE trip_id = NEW.trip_id FOR UPDATE;

  IF v_status <> 'SCHEDULED' THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'RAIL RULE VIOLATION: trip is not open for allocation.';
  END IF;

  SELECT MAX(status) INTO v_manifest_status FROM manifest WHERE trip_id=NEW.trip_id FOR UPDATE;
  IF v_manifest_status = 'RECEIVED' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'RAIL RULE VIOLATION: manifest already received.';
  END IF;

  -- FOR SHARE is a current read under REPEATABLE READ. Unlike FOR UPDATE,
  -- it is supported when reading the invoking table from this trigger (verified on MySQL 8).
  -- A plain SUM could reuse an older snapshot and permit overbooking.
  SELECT COALESCE(SUM(allocated_space), 0) INTO v_used
    FROM rail_allocation WHERE trip_id = NEW.trip_id FOR SHARE;

  IF v_used + NEW.allocated_space > v_cap THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'RAIL RULE VIOLATION: allocation exceeds trip capacity.';
  END IF;
END //

DROP TRIGGER IF EXISTS trg_rail_alloc_manifest_ai//
CREATE TRIGGER trg_rail_alloc_manifest_ai AFTER INSERT ON rail_allocation
FOR EACH ROW
BEGIN
  INSERT INTO manifest (station_id, trip_id, status)
  SELECT destination_station_id, trip_id, 'PENDING' FROM train_trip WHERE trip_id=NEW.trip_id
  ON DUPLICATE KEY UPDATE manifest_id=manifest_id;
END //

DROP TRIGGER IF EXISTS trg_rail_alloc_capacity_bu//
CREATE TRIGGER trg_rail_alloc_capacity_bu
BEFORE UPDATE ON rail_allocation
FOR EACH ROW
BEGIN
  DECLARE v_cap  DECIMAL(10,2);
  DECLARE v_used DECIMAL(10,2);
  DECLARE v_status VARCHAR(50);
  DECLARE v_received VARCHAR(50);

  SET NEW.allocated_space = fn_order_item_space(NEW.order_item_id, NEW.allocated_quantity);

  SELECT total_capacity, status INTO v_cap, v_status
    FROM train_trip WHERE trip_id = NEW.trip_id FOR UPDATE;
  SELECT MAX(status) INTO v_received FROM manifest WHERE trip_id IN (OLD.trip_id, NEW.trip_id) FOR UPDATE;
  IF v_status <> 'SCHEDULED' OR v_received = 'RECEIVED' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'RAIL RULE VIOLATION: allocation is closed or received.';
  END IF;

  SELECT COALESCE(SUM(allocated_space), 0) INTO v_used
    FROM rail_allocation
   WHERE trip_id = NEW.trip_id AND allocation_id <> OLD.allocation_id FOR SHARE;

  IF v_used + NEW.allocated_space > v_cap THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'RAIL RULE VIOLATION: allocation exceeds trip capacity.';
  END IF;
END //

DROP TRIGGER IF EXISTS trg_rail_alloc_receipt_bd//
CREATE TRIGGER trg_rail_alloc_receipt_bd BEFORE DELETE ON rail_allocation
FOR EACH ROW
BEGIN
  DECLARE v_trip INT;
  DECLARE v_received VARCHAR(50);
  SELECT trip_id INTO v_trip FROM train_trip WHERE trip_id=OLD.trip_id FOR UPDATE;
  SELECT MAX(status) INTO v_received FROM manifest WHERE trip_id=OLD.trip_id FOR UPDATE;
  IF v_received = 'RECEIVED' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'RAIL RULE VIOLATION: received allocation cannot be reversed.';
  END IF;
END //

DROP TRIGGER IF EXISTS trg_rail_alloc_manifest_au//
CREATE TRIGGER trg_rail_alloc_manifest_au AFTER UPDATE ON rail_allocation
FOR EACH ROW
BEGIN
  INSERT INTO manifest (station_id, trip_id, status)
  SELECT destination_station_id, trip_id, 'PENDING' FROM train_trip WHERE trip_id=NEW.trip_id
  ON DUPLICATE KEY UPDATE manifest_id=manifest_id;
END //

DELIMITER ;

-- Source: feature_4_2_rail_allocation/07_trg_trip_capacity_shrink.sql
-- a trip's capacity cannot be cut below what is already booked
DELIMITER //

DROP TRIGGER IF EXISTS trg_train_trip_capacity_bu//
CREATE TRIGGER trg_train_trip_capacity_bu
BEFORE UPDATE ON train_trip
FOR EACH ROW
BEGIN
  DECLARE v_used DECIMAL(10,2);

  IF NEW.total_capacity < OLD.total_capacity THEN
    SELECT COALESCE(SUM(allocated_space), 0) INTO v_used
      FROM rail_allocation WHERE trip_id = OLD.trip_id FOR SHARE;

    IF NEW.total_capacity < v_used THEN
      SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'RAIL RULE VIOLATION: capacity cannot go below already allocated space.';
    END IF;
  END IF;
END //

DELIMITER ;

-- Source: feature_4_2_rail_allocation/08_sp_schedule_train_order.sql
-- multi trip spillover scheduler (transaction + row locking)
-- Feature 4.2: Rail Capacity Allocation & Spillover
DELIMITER //

DROP PROCEDURE IF EXISTS sp_schedule_train_order//
CREATE PROCEDURE sp_schedule_train_order(
  IN  p_order_id INT,
  IN  p_user_id  INT,            -- logistics manager; NULL is allowed
  OUT p_result   VARCHAR(50)
)
proc_body: BEGIN
  DECLARE v_status        VARCHAR(50);
  DECLARE v_delivery_date DATE;
  DECLARE v_dest_station  INT;
  DECLARE v_kandy_station INT;
  DECLARE v_item_id       INT DEFAULT 0;
  DECLARE v_next_item     INT;
  DECLARE v_item_qty      INT;
  DECLARE v_rate          DECIMAL(6,4);
  DECLARE v_remaining     INT;
  DECLARE v_last_dep      DATETIME;
  DECLARE v_last_trip     INT;
  DECLARE v_trip_id       INT;
  DECLARE v_trip_dep      DATETIME;
  DECLARE v_trip_cap      DECIMAL(10,2);
  DECLARE v_used          DECIMAL(10,2);
  DECLARE v_fit           INT;
  DECLARE v_alloc_qty     INT;
  DECLARE v_trip_count    INT DEFAULT 0;
  DECLARE v_any_item      INT DEFAULT 0;

  -- 1213 = deadlock, 1205 = lock wait timeout >> caller may simply retry
  DECLARE EXIT HANDLER FOR 1213, 1205
  BEGIN
    ROLLBACK;
    SET p_result = 'DEADLOCK_RETRY';
  END;

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    SET p_result = 'ERROR_TRANSACTION_FAILED';
    IF p_user_id IS NOT NULL THEN
      INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
      VALUES (p_user_id, 'SCHEDULE_RAIL_ORDER', p_order_id, 'ERROR_TRANSACTION_FAILED', 'customer_order');
      COMMIT;
    END IF;
  END;

  START TRANSACTION;

  -- 1. lock the order row and validate its state
  SET v_status = NULL;
  SELECT status, delivery_date INTO v_status, v_delivery_date
    FROM customer_order WHERE order_id = p_order_id FOR UPDATE;

  IF v_status IS NULL THEN
    ROLLBACK; SET p_result = 'ORDER_NOT_FOUND';
    IF p_user_id IS NOT NULL THEN
      INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
      VALUES (p_user_id, 'SCHEDULE_RAIL_ORDER', p_order_id, p_result, 'customer_order');
      COMMIT;
    END IF;
    LEAVE proc_body;
  END IF;

  IF v_status <> 'PENDING_RAIL_SCHEDULING' THEN
    ROLLBACK; SET p_result = 'INVALID_ORDER_STATUS';
    IF p_user_id IS NOT NULL THEN
      INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
      VALUES (p_user_id, 'SCHEDULE_RAIL_ORDER', p_order_id, p_result, 'customer_order');
      COMMIT;
    END IF;
    LEAVE proc_body;
  END IF;

  -- 2. destination hub = station of the customer's delivery route
  SET v_dest_station = NULL;
  SELECT dr.station_id INTO v_dest_station
    FROM customer_order co
    JOIN customer c        ON c.customer_id = co.customer_id
    JOIN delivery_route dr ON dr.route_id   = co.delivery_route_id
    JOIN station_store dest ON dest.station_id = dr.station_id AND dest.is_active = 1
      AND dest.city IN ('Colombo','Negombo','Galle','Matara','Jaffna','Trincomalee')
   WHERE co.order_id = p_order_id;

  IF v_dest_station IS NULL THEN
    ROLLBACK; SET p_result = 'DESTINATION_HUB_NOT_RESOLVED';
    IF p_user_id IS NOT NULL THEN
      INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
      VALUES (p_user_id, 'SCHEDULE_RAIL_ORDER', p_order_id, p_result, 'customer_order');
      COMMIT;
    END IF;
    LEAVE proc_body;
  END IF;

  -- LM-03: Origin must be Kandy
  SET v_kandy_station = NULL;
  SELECT station_id INTO v_kandy_station FROM station_store WHERE city = 'Kandy' AND is_active = 1 ORDER BY station_id LIMIT 1;
  IF v_kandy_station IS NULL THEN
    ROLLBACK; SET p_result = 'ORIGIN_HUB_NOT_FOUND';
    IF p_user_id IS NOT NULL THEN
      INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
      VALUES (p_user_id, 'SCHEDULE_RAIL_ORDER', p_order_id, p_result, 'customer_order');
      COMMIT;
    END IF;
    LEAVE proc_body;
  END IF;

  -- 3. walk the order items one by one
  item_loop: LOOP
    SET v_next_item = NULL;
    SELECT MIN(order_item_id) INTO v_next_item
      FROM order_item WHERE order_id = p_order_id AND order_item_id > v_item_id;

    IF v_next_item IS NULL THEN
      LEAVE item_loop;
    END IF;

    SET v_item_id  = v_next_item;
    SET v_any_item = 1;

    SELECT oi.quantity, p.space_consumption_rate INTO v_item_qty, v_rate
      FROM order_item oi JOIN product p ON p.product_id = oi.product_id
     WHERE oi.order_item_id = v_item_id;

    IF v_item_qty <= 0 THEN
      ROLLBACK; SET p_result = 'INVALID_ORDER_QUANTITY';
      LEAVE proc_body;
    END IF;

    IF v_rate IS NULL OR v_rate <= 0 THEN
      ROLLBACK; SET p_result = 'INVALID_PRODUCT_SPACE_RATE';
      IF p_user_id IS NOT NULL THEN
        INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
        VALUES (p_user_id, 'SCHEDULE_RAIL_ORDER', p_order_id, p_result, 'customer_order');
        COMMIT;
      END IF;
      LEAVE proc_body;
    END IF;

    SET v_remaining = v_item_qty;
    SET v_last_dep  = '1000-01-01 00:00:00';
    SET v_last_trip = 0;

    -- 4. spillover: earliest trip first, then the next one, ...
    trip_loop: WHILE v_remaining > 0 DO
      SET v_trip_id = NULL;

      SELECT tt.trip_id, tt.departure_datetime, tt.total_capacity
        INTO v_trip_id, v_trip_dep, v_trip_cap
        FROM train_trip tt
       WHERE tt.origin_station_id = v_kandy_station
         AND tt.destination_station_id = v_dest_station
         AND tt.status = 'SCHEDULED'
         AND NOT EXISTS (SELECT 1 FROM manifest m WHERE m.trip_id=tt.trip_id AND m.status='RECEIVED')
         AND tt.departure_datetime > CONVERT_TZ(UTC_TIMESTAMP(), '+00:00', '+05:30')
         AND tt.arrival_datetime < v_delivery_date + INTERVAL 1 DAY
         AND (tt.departure_datetime > v_last_dep
              OR (tt.departure_datetime = v_last_dep AND tt.trip_id > v_last_trip))
       ORDER BY tt.departure_datetime, tt.trip_id
       LIMIT 1
       FOR UPDATE;                                   -- row lock on the trip

      IF v_trip_id IS NULL THEN
        LEAVE trip_loop;                             -- no more trips
      END IF;

      SET v_last_dep  = v_trip_dep;
      SET v_last_trip = v_trip_id;

      -- locking read so we see allocations committed by other sessions
      SELECT COALESCE(SUM(allocated_space), 0) INTO v_used
        FROM rail_allocation WHERE trip_id = v_trip_id FOR UPDATE;

      SET v_fit = FLOOR((v_trip_cap - v_used) / v_rate);

      IF v_fit > 0 THEN
        SET v_alloc_qty = LEAST(v_fit, v_remaining);

        INSERT INTO rail_allocation
               (order_item_id, trip_id, allocated_quantity, allocated_space, allocated_by)
        VALUES (v_item_id, v_trip_id, v_alloc_qty,
                fn_order_item_space(v_item_id, v_alloc_qty), p_user_id);

        SET v_remaining = v_remaining - v_alloc_qty;
      END IF;
    END WHILE trip_loop;

    IF v_remaining > 0 THEN
      ROLLBACK; SET p_result = 'INSUFFICIENT_RAIL_CAPACITY';
      IF p_user_id IS NOT NULL THEN
        INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
        VALUES (p_user_id, 'SCHEDULE_RAIL_ORDER', p_order_id, p_result, 'customer_order');
        COMMIT;
      END IF;
      LEAVE proc_body;
    END IF;
  END LOOP item_loop;

  IF v_any_item = 0 THEN
    ROLLBACK; SET p_result = 'ORDER_HAS_NO_ITEMS';
    IF p_user_id IS NOT NULL THEN
      INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
      VALUES (p_user_id, 'SCHEDULE_RAIL_ORDER', p_order_id, p_result, 'customer_order');
      COMMIT;
    END IF;
    LEAVE proc_body;
  END IF;

  -- 5. single trip or multi-trip?
  SELECT COUNT(DISTINCT ra.trip_id) INTO v_trip_count
    FROM rail_allocation ra
    JOIN order_item oi ON oi.order_item_id = ra.order_item_id
   WHERE oi.order_id = p_order_id;

  IF v_trip_count = 1 THEN
    UPDATE customer_order SET status = 'SCHEDULED_FOR_RAIL' WHERE order_id = p_order_id;
    INSERT INTO order_status_history (status, order_id, changed_by)
    VALUES ('SCHEDULED_FOR_RAIL', p_order_id, p_user_id);
    SET p_result = 'SUCCESS_SINGLE_TRIP';
  ELSE
    UPDATE customer_order SET status = 'SCHEDULED_MULTI_TRIP' WHERE order_id = p_order_id;
    INSERT INTO order_status_history (status, order_id, changed_by)
    VALUES ('SCHEDULED_MULTI_TRIP', p_order_id, p_user_id);
    SET p_result = 'SUCCESS_MULTI_TRIP_SPILLOVER';
  END IF;

  IF p_user_id IS NOT NULL THEN
    INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
    VALUES (p_user_id, 'SCHEDULE_RAIL_ORDER', p_order_id, 'SUCCESS', 'customer_order');
  END IF;

  COMMIT;
END //

-- keep the old name working (an older draft already lived in 03_procedures.sql)
DROP PROCEDURE IF EXISTS sp_allocate_rail_capacity//
CREATE PROCEDURE sp_allocate_rail_capacity(IN p_order_id INT, OUT p_status_result VARCHAR(50))
BEGIN
  CALL sp_schedule_train_order(p_order_id, NULL, p_status_result);
END //

DELIMITER ;

-- Source: feature_4_2_rail_allocation/09_v_trip_capacity_usage.sql
-- View: v_trip_capacity_usage (Feature 4.2: Rail Allocation Capacity Analytics)
CREATE OR REPLACE VIEW v_trip_capacity_usage AS
SELECT 
    tt.trip_id,
    tt.origin_station_id,
    tt.destination_station_id,
    tt.departure_datetime,
    tt.status,
    tt.total_capacity,
    COALESCE(SUM(ra.allocated_space), 0) AS used_space,
    tt.total_capacity - COALESCE(SUM(ra.allocated_space), 0) AS remaining_space,
    ROUND((COALESCE(SUM(ra.allocated_space), 0) / tt.total_capacity) * 100, 2) AS utilisation_pct
FROM train_trip tt
LEFT JOIN rail_allocation ra ON tt.trip_id = ra.trip_id
GROUP BY tt.trip_id, tt.origin_station_id, tt.destination_station_id, tt.departure_datetime, tt.status, tt.total_capacity;

-- Source: feature_4_2_rail_allocation/12_trg_allocation_quantity_guard.sql
DELIMITER //

DROP TRIGGER IF EXISTS trg_rail_alloc_quantity_bi//
CREATE TRIGGER trg_rail_alloc_quantity_bi BEFORE INSERT ON rail_allocation
FOR EACH ROW FOLLOWS trg_rail_alloc_capacity_bi
BEGIN
  DECLARE v_ordered INT;
  DECLARE v_already INT;
  SELECT quantity INTO v_ordered FROM order_item WHERE order_item_id = NEW.order_item_id FOR UPDATE;
  SELECT COALESCE(SUM(allocated_quantity), 0) INTO v_already FROM rail_allocation WHERE order_item_id = NEW.order_item_id FOR SHARE;
  IF v_already + NEW.allocated_quantity > v_ordered THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'RAIL RULE VIOLATION: allocation exceeds ordered quantity (duplicate allocation).';
  END IF;
END//

DROP TRIGGER IF EXISTS trg_rail_alloc_quantity_bu//
CREATE TRIGGER trg_rail_alloc_quantity_bu BEFORE UPDATE ON rail_allocation
FOR EACH ROW FOLLOWS trg_rail_alloc_capacity_bu
BEGIN
  DECLARE v_ordered INT;
  DECLARE v_already INT;
  SELECT quantity INTO v_ordered FROM order_item WHERE order_item_id = NEW.order_item_id FOR UPDATE;
  SELECT COALESCE(SUM(allocated_quantity), 0) INTO v_already
    FROM rail_allocation
   WHERE order_item_id = NEW.order_item_id AND allocation_id <> OLD.allocation_id FOR SHARE;
  IF v_already + NEW.allocated_quantity > v_ordered THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'RAIL RULE VIOLATION: allocation exceeds ordered quantity (duplicate allocation).';
  END IF;
END//

DELIMITER ;

-- Source: feature_4_2_rail_allocation/14_trg_rail_alloc_origin_bi.sql
-- Trigger: trg_rail_alloc_origin_bi & trg_rail_alloc_origin_bu (LM-03 DB-level Guard: origin must be Kandy)
DELIMITER //

DROP TRIGGER IF EXISTS trg_rail_alloc_origin_bi//
CREATE TRIGGER trg_rail_alloc_origin_bi BEFORE INSERT ON rail_allocation
FOR EACH ROW FOLLOWS trg_rail_alloc_quantity_bi
BEGIN
    DECLARE v_origin_city VARCHAR(100);

    SELECT ss.city INTO v_origin_city
    FROM train_trip tt
    JOIN station_store ss ON ss.station_id = tt.origin_station_id
    WHERE tt.trip_id = NEW.trip_id;

    IF v_origin_city IS NULL OR v_origin_city <> 'Kandy' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'RAIL RULE VIOLATION: trip does not depart from Kandy.';
    END IF;
END//

DROP TRIGGER IF EXISTS trg_rail_alloc_origin_bu//
CREATE TRIGGER trg_rail_alloc_origin_bu BEFORE UPDATE ON rail_allocation
FOR EACH ROW FOLLOWS trg_rail_alloc_quantity_bu
BEGIN
    DECLARE v_origin_city VARCHAR(100);

    SELECT ss.city INTO v_origin_city
    FROM train_trip tt
    JOIN station_store ss ON ss.station_id = tt.origin_station_id
    WHERE tt.trip_id = NEW.trip_id;

    IF v_origin_city IS NULL OR v_origin_city <> 'Kandy' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'RAIL RULE VIOLATION: trip does not depart from Kandy.';
    END IF;
END//

DELIMITER ;

-- Source: feature_4_2_rail_allocation/15_sp_reverse_rail_allocation.sql
-- Stored Procedure: sp_reverse_rail_allocation (LM-18: Reschedule / Reversal Engine)
-- Reverses existing rail allocations for an order, resets order status to PENDING_RAIL_SCHEDULING,
-- records trip-by-trip audit logs, and guards against reversing departed/inactive trips.
DELIMITER //

DROP PROCEDURE IF EXISTS sp_reverse_rail_allocation//
CREATE PROCEDURE sp_reverse_rail_allocation(
    IN  p_order_id INT,
    IN  p_user_id  INT,
    OUT p_result   VARCHAR(50)
)
proc_body: BEGIN
    DECLARE v_status VARCHAR(50);
    DECLARE v_alloc_count INT;
    DECLARE v_invalid_trip_count INT;
    DECLARE done INT DEFAULT FALSE;

    -- Variables for per-allocation audit logging
    DECLARE v_audit_alloc_id INT;
    DECLARE v_audit_trip_id INT;
    DECLARE v_audit_qty INT;
    DECLARE v_audit_space DECIMAL(10,2);

    DECLARE cur_allocs CURSOR FOR
        SELECT ra.allocation_id, ra.trip_id, ra.allocated_quantity, ra.allocated_space
        FROM rail_allocation ra
        JOIN order_item oi ON oi.order_item_id = ra.order_item_id
        WHERE oi.order_id = p_order_id;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

    DECLARE EXIT HANDLER FOR 1213, 1205
    BEGIN
        ROLLBACK;
        SET p_result = 'DEADLOCK_RETRY';
    END;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_result = 'ERROR_TRANSACTION_FAILED';
        IF p_user_id IS NOT NULL THEN
            INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
            VALUES (p_user_id, 'REVERSE_RAIL_ORDER', p_order_id, 'ERROR_TRANSACTION_FAILED', 'customer_order');
            COMMIT;
        END IF;
    END;

    START TRANSACTION;

    -- 1. Validate and lock order
    SET v_status = NULL;
    SELECT status INTO v_status
      FROM customer_order
     WHERE order_id = p_order_id
       FOR UPDATE;

    IF v_status IS NULL THEN
        ROLLBACK;
        SET p_result = 'ORDER_NOT_FOUND';
        IF p_user_id IS NOT NULL THEN
            INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
            VALUES (p_user_id, 'REVERSE_RAIL_ORDER', p_order_id, p_result, 'customer_order');
            COMMIT;
        END IF;
        LEAVE proc_body;
    END IF;

    -- Only orders currently scheduled for rail can be reversed
    IF v_status NOT IN ('SCHEDULED_FOR_RAIL', 'SCHEDULED_MULTI_TRIP') THEN
        ROLLBACK;
        SET p_result = 'INVALID_ORDER_STATUS';
        IF p_user_id IS NOT NULL THEN
            INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
            VALUES (p_user_id, 'REVERSE_RAIL_ORDER', p_order_id, p_result, 'customer_order');
            COMMIT;
        END IF;
        LEAVE proc_body;
    END IF;

    -- 2. Guard: refuse reversal if any of the order's trips has already departed or is not SCHEDULED
    SELECT COUNT(*) INTO v_invalid_trip_count
      FROM rail_allocation ra
      JOIN order_item oi ON oi.order_item_id = ra.order_item_id
      JOIN train_trip tt ON tt.trip_id = ra.trip_id
     WHERE oi.order_id = p_order_id
       AND (tt.status <> 'SCHEDULED' OR tt.departure_datetime <= CONVERT_TZ(UTC_TIMESTAMP(), '+00:00', '+05:30')
            OR EXISTS (SELECT 1 FROM manifest m WHERE m.trip_id=tt.trip_id AND m.status='RECEIVED'));

    IF v_invalid_trip_count > 0 THEN
        ROLLBACK;
        SET p_result = 'CANNOT_REVERSE_DEPARTED_OR_INACTIVE_TRIP';
        IF p_user_id IS NOT NULL THEN
            INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
            VALUES (p_user_id, 'REVERSE_RAIL_ORDER', p_order_id, p_result, 'customer_order');
            COMMIT;
        END IF;
        LEAVE proc_body;
    END IF;

    -- 3. Record trip-by-trip audit log for what is being reversed
    IF p_user_id IS NOT NULL THEN
        OPEN cur_allocs;
        audit_loop: LOOP
            FETCH cur_allocs INTO v_audit_alloc_id, v_audit_trip_id, v_audit_qty, v_audit_space;
            IF done THEN
                LEAVE audit_loop;
            END IF;
            INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
            VALUES (
                p_user_id,
                'REVERSE_RAIL_ALLOCATION_ITEM',
                v_audit_alloc_id,
                CONCAT('TRIP:', v_audit_trip_id, ';QTY:', v_audit_qty, ';SPACE:', v_audit_space),
                'rail_allocation'
            );
        END LOOP;
        CLOSE cur_allocs;
    END IF;

    -- 4. Delete allocation rows (freeing up train trip capacity)
    DELETE ra FROM rail_allocation ra
      JOIN order_item oi ON oi.order_item_id = ra.order_item_id
     WHERE oi.order_id = p_order_id;

    -- 5. Reset customer_order status to PENDING_RAIL_SCHEDULING
    UPDATE customer_order
       SET status = 'PENDING_RAIL_SCHEDULING'
     WHERE order_id = p_order_id;

    -- 6. Record status history
    INSERT INTO order_status_history (status, order_id, changed_by)
    VALUES ('PENDING_RAIL_SCHEDULING', p_order_id, p_user_id);

    -- 7. Audit log summary entry
    IF p_user_id IS NOT NULL THEN
        INSERT INTO audit_log (user_id, action, entity_id, outcome, entity_name)
        VALUES (p_user_id, 'REVERSE_RAIL_ORDER', p_order_id, 'SUCCESS', 'customer_order');
    END IF;

    COMMIT;
    SET p_result = 'SUCCESS_REVERSED';
END //

DELIMITER ;

-- Source: feature_4_2_rail_allocation/16_trip_hub_guard.sql
-- Valid rail hub connections; capacity remains derived from rail_allocation.
DELIMITER //
DROP TRIGGER IF EXISTS trg_train_trip_hubs_bi//
CREATE TRIGGER trg_train_trip_hubs_bi BEFORE INSERT ON train_trip
FOR EACH ROW
BEGIN
  IF NOT EXISTS (SELECT 1 FROM station_store WHERE station_id=NEW.origin_station_id AND city='Kandy' AND is_active=1)
     OR NOT EXISTS (SELECT 1 FROM station_store WHERE station_id=NEW.destination_station_id AND is_active=1
                    AND city IN ('Colombo','Negombo','Galle','Matara','Jaffna','Trincomalee')) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='RAIL RULE VIOLATION: active Kandy origin and supported destination required.';
  END IF;
END//
DROP TRIGGER IF EXISTS trg_train_trip_hubs_bu//
CREATE TRIGGER trg_train_trip_hubs_bu BEFORE UPDATE ON train_trip
FOR EACH ROW
BEGIN
  IF NEW.origin_station_id <> OLD.origin_station_id OR NEW.destination_station_id <> OLD.destination_station_id THEN
    IF EXISTS (SELECT 1 FROM rail_allocation WHERE trip_id=OLD.trip_id) THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='RAIL RULE VIOLATION: allocated trip hubs are immutable.';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM station_store WHERE station_id=NEW.origin_station_id AND city='Kandy' AND is_active=1)
       OR NOT EXISTS (SELECT 1 FROM station_store WHERE station_id=NEW.destination_station_id AND is_active=1
                      AND city IN ('Colombo','Negombo','Galle','Matara','Jaffna','Trincomalee')) THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='RAIL RULE VIOLATION: active Kandy origin and supported destination required.';
    END IF;
  END IF;
END//
DELIMITER ;

-- Repair only the unambiguous future, still-scheduled handoff. Historical arrivals
-- require inventory reconciliation; never manufacture a second receipt for them.
INSERT INTO manifest (station_id, trip_id, status)
SELECT DISTINCT t.destination_station_id, t.trip_id, 'PENDING'
FROM train_trip t
JOIN rail_allocation a ON a.trip_id=t.trip_id
JOIN order_item i ON i.order_item_id=a.order_item_id
JOIN customer_order o ON o.order_id=i.order_id
LEFT JOIN manifest m ON m.trip_id=t.trip_id AND m.station_id=t.destination_station_id
WHERE m.manifest_id IS NULL AND t.status='SCHEDULED'
  AND t.departure_datetime > CONVERT_TZ(UTC_TIMESTAMP(), '+00:00', '+05:30')
  AND o.status IN ('SCHEDULED_FOR_RAIL','SCHEDULED_MULTI_TRIP')
ON DUPLICATE KEY UPDATE manifest_id=manifest.manifest_id;
COMMIT;
