"""Build the selected-database rail migration without executing any SQL.

Run: python build_phase2_migration.py
Check generated artifact: python build_phase2_migration.py --check
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent
SOURCES = (
    '04_fn_order_item_space.sql', '05_fn_trip_remaining_capacity.sql',
    '06_trg_capacity_check.sql', '07_trg_trip_capacity_shrink.sql',
    '08_sp_schedule_train_order.sql', '09_v_trip_capacity_usage.sql',
    '12_trg_allocation_quantity_guard.sql', '14_trg_rail_alloc_origin_bi.sql',
    '15_sp_reverse_rail_allocation.sql', '16_trip_hub_guard.sql',
)
CONSTRAINTS = (
    ('train_trip', 'chk_trip_capacity_positive', 'total_capacity > 0'),
    ('train_trip', 'chk_trip_time_order', 'arrival_datetime > departure_datetime'),
    ('train_trip', 'chk_trip_distinct_stations', 'origin_station_id <> destination_station_id'),
    ('train_trip', 'chk_trip_status', "status IN ('SCHEDULED','IN_TRANSIT','ARRIVED','CANCELLED')"),
    ('rail_allocation', 'chk_alloc_qty_positive', 'allocated_quantity > 0'),
    ('rail_allocation', 'chk_alloc_space_positive', 'allocated_space > 0'),
)


def render():
    sql = '''-- Generated by build_phase2_migration.py. Select the intended database first.
-- Applies only rail routines/guards/view and missing named constraints/indexes.
-- No table reset, seed data, database selection, global roles, or user account changes.
-- Run while rail writes are paused: MySQL DDL commits independently.
DELIMITER //
DROP PROCEDURE IF EXISTS sp_phase2_schema_checks//
CREATE PROCEDURE sp_phase2_schema_checks()
BEGIN
  IF EXISTS (SELECT 1 FROM train_trip t JOIN rail_allocation a ON a.trip_id=t.trip_id
             GROUP BY t.trip_id,t.total_capacity HAVING SUM(a.allocated_space)>t.total_capacity)
     OR EXISTS (SELECT 1 FROM order_item i JOIN rail_allocation a ON a.order_item_id=i.order_item_id
                GROUP BY i.order_item_id,i.quantity HAVING SUM(a.allocated_quantity)>i.quantity) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Rail migration blocked: existing capacity/quantity over-allocation requires review.';
  END IF;
'''
    for table, name, check in CONSTRAINTS:
        sql += f"  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='{table}' AND constraint_name='{name}') THEN\n    ALTER TABLE {table} ADD CONSTRAINT {name} CHECK ({check});\n  END IF;\n"
    for table, name, columns in (
        ('train_trip', 'idx_f42_trip_search', 'destination_station_id, status, departure_datetime'),
        ('rail_allocation', 'idx_f42_alloc_trip_space', 'trip_id, allocated_space'),
    ):
        sql += f"  IF NOT EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='{table}' AND index_name='{name}') THEN\n    CREATE INDEX {name} ON {table} ({columns});\n  END IF;\n"
    sql += 'END//\nCALL sp_phase2_schema_checks()//\nDROP PROCEDURE sp_phase2_schema_checks//\nDELIMITER ;\n'
    for filename in SOURCES:
        source = (ROOT / 'feature_4_2_rail_allocation' / filename).read_text(encoding='utf-8')
        source = re.sub(r'(?im)^USE kandypack_db;\s*', '', source)
        sql += f'\n-- Source: feature_4_2_rail_allocation/{filename}\n' + source.rstrip() + '\n'
    sql += '''
-- Repair only the unambiguous future, still-scheduled handoff. Historical arrivals
-- require inventory reconciliation; never manufacture a second receipt for them.
INSERT INTO manifest (station_id, trip_id, status)
SELECT DISTINCT t.destination_station_id, t.trip_id, 'PENDING'
FROM train_trip t
JOIN rail_allocation a ON a.trip_id=t.trip_id
JOIN order_item i ON i.order_item_id=a.order_item_id
JOIN customer_order o ON o.order_id=i.order_id
LEFT JOIN manifest m ON m.trip_id=t.trip_id AND m.station_id=t.destination_station_id
WHERE m.manifest_id IS NULL AND t.status='SCHEDULED'
  AND t.departure_datetime > CONVERT_TZ(UTC_TIMESTAMP(), '+00:00', '+05:30')
  AND o.status IN ('SCHEDULED_FOR_RAIL','SCHEDULED_MULTI_TRIP')
ON DUPLICATE KEY UPDATE manifest_id=manifest.manifest_id;
COMMIT;
'''
    return sql


if __name__ == '__main__':
    output = ROOT / '15_phase2_rail_workflow.sql'
    if '--check' in sys.argv:
        assert output.read_text(encoding='utf-8') == render(), 'Regenerate the rail migration.'
        print('Rail migration matches its source artifacts.')
    else:
        output.write_text(render(), encoding='utf-8')
        print('Generated', output.name)
