"""Generate non-destructive Phase 4 selected-database migration and sync master."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent


def receipt(source):
    start = source.index('DROP PROCEDURE IF EXISTS sp_receive_manifest')
    end = source.index('END //', start) + len('END //')
    return source[start:end]


def render():
    return '''-- Generated by build_phase4_migration.py; select the intended database first.
-- Pause station writes for DDL deployment. No database reset or seed changes.
DELIMITER //
DROP PROCEDURE IF EXISTS sp_phase4_schema_upgrade//
CREATE PROCEDURE sp_phase4_schema_upgrade()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE()
                   AND table_name='user' AND column_name='station_id') THEN
        ALTER TABLE user ADD COLUMN station_id INT NULL,
            ADD CONSTRAINT fk_user_station FOREIGN KEY (station_id) REFERENCES station_store(station_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE()
                   AND table_name='stock_adjustment' AND column_name='request_key') THEN
        ALTER TABLE stock_adjustment ADD COLUMN request_key VARCHAR(128)
            CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
            ADD CONSTRAINT uq_stock_adjustment_request UNIQUE(request_key);
    END IF;
END //
CALL sp_phase4_schema_upgrade()//
DROP PROCEDURE sp_phase4_schema_upgrade//
''' + receipt((ROOT/'03_procedures.sql').read_text(encoding='utf-8')) + '\nDELIMITER ;\n'


if __name__ == '__main__':
    path = ROOT/'16_phase4_station_workflow.sql'
    master = ROOT/'00_master_init.sql'
    source = master.read_text(encoding='utf-8')
    updated = source.replace(receipt(source), receipt((ROOT/'03_procedures.sql').read_text(encoding='utf-8')))
    if 'fk_user_station' not in updated:
        updated = updated.replace('CREATE TABLE storage_location (',
            'ALTER TABLE user ADD COLUMN station_id INT NULL,\n    ADD CONSTRAINT fk_user_station FOREIGN KEY (station_id) REFERENCES station_store(station_id);\n\nCREATE TABLE storage_location (')
    if 'uq_stock_adjustment_request' not in updated:
        updated = updated.replace('CREATE TABLE stock_adjustment (\n    adjustment_id INT AUTO_INCREMENT PRIMARY KEY,',
            'CREATE TABLE stock_adjustment (\n    adjustment_id INT AUTO_INCREMENT PRIMARY KEY,\n    request_key VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,\n    CONSTRAINT uq_stock_adjustment_request UNIQUE (request_key),')
    if '--check' in sys.argv:
        assert path.read_text(encoding='utf-8') == render()
        assert source == updated
    else:
        path.write_text(render(), encoding='utf-8')
        master.write_text(updated, encoding='utf-8')
